/* eslint-disable @typescript-eslint/no-explicit-any */
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export interface EventInvoiceData {
  invoiceNumber: string;
  businessName: string;
  businessCurrency: string;
  customerName: string;
  customerPhone?: string;
  customerEmail?: string;
  eventName: string;
  eventType: string;
  eventDate: string;
  date: string;
  items: {
    name: string;
    quantity: number;
    unit: string;
    unitCost: number;
    totalCost: number;
  }[];
  totalCost: number;
  customerBudget: number;
  plateCount: number;
}

/**
 * Generates a professional PDF invoice for catering events.
 */
export function generateEventInvoicePDF(data: EventInvoiceData): Blob {
  const doc = new jsPDF();
  const currency = data.businessCurrency || "UGX";

  // Header background
  doc.setFillColor(17, 24, 39);
  doc.rect(0, 0, 210, 50, "F");

  // Business name
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text(data.businessName, 20, 20);

  // Event details
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text("EVENT INVOICE", 20, 32);
  doc.setFontSize(9);
  doc.text(`${data.eventType} — ${data.eventName}`, 20, 40);

  // Invoice number & date
  doc.setFontSize(10);
  doc.text(data.invoiceNumber, 155, 20);
  doc.text(`Date: ${data.date}`, 155, 28);
  doc.text(`Event: ${data.eventDate}`, 155, 36);

  doc.setTextColor(31, 41, 55);

  // Bill To
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("BILL TO:", 20, 65);
  doc.setFont("helvetica", "normal");
  doc.text(data.customerName, 20, 73);
  if (data.customerPhone) doc.text(data.customerPhone, 20, 79);
  if (data.customerEmail) doc.text(data.customerEmail, 20, 85);

  // Budget & plates
  doc.setFont("helvetica", "bold");
  doc.text("EVENT SUMMARY:", 120, 65);
  doc.setFont("helvetica", "normal");
  doc.text(`Budget: ${currency} ${data.customerBudget.toLocaleString()}`, 120, 73);
  doc.text(`Plates: ${data.plateCount}`, 120, 79);
  if (data.plateCount > 0) {
    doc.text(`Cost/Plate: ${currency} ${Math.round(data.totalCost / data.plateCount).toLocaleString()}`, 120, 85);
  }

  // Items table
  const tableData = data.items.map((item, i) => [
    String(i + 1),
    item.name,
    `${item.quantity} ${item.unit}`,
    `${currency} ${item.unitCost.toLocaleString()}`,
    `${currency} ${item.totalCost.toLocaleString()}`,
  ]);

  autoTable(doc, {
    startY: 95,
    head: [["#", "Item", "Qty", "Unit Cost", "Total"]],
    body: tableData,
    theme: "striped",
    headStyles: {
      fillColor: [17, 24, 39],
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 10,
    },
    bodyStyles: { fontSize: 9 },
    alternateRowStyles: { fillColor: [243, 244, 246] },
    columnStyles: {
      0: { cellWidth: 15 },
      1: { cellWidth: 65 },
      2: { cellWidth: 30, halign: "center" },
      3: { cellWidth: 40, halign: "right" },
      4: { cellWidth: 40, halign: "right" },
    },
  });

  const finalY = (doc as any).lastAutoTable?.finalY || 150;

  // Totals section
  const profit = data.customerBudget - data.totalCost;
  const summaryY = finalY + 10;

  doc.setFillColor(243, 244, 246);
  doc.rect(110, summaryY, 80, 36, "F");

  doc.setFontSize(9);
  doc.setTextColor(107, 114, 128);
  doc.text("Total Cost:", 115, summaryY + 8);
  doc.text("Customer Budget:", 115, summaryY + 16);
  doc.text("Profit/Loss:", 115, summaryY + 28);

  doc.setTextColor(31, 41, 55);
  doc.setFont("helvetica", "bold");
  doc.text(`${currency} ${data.totalCost.toLocaleString()}`, 165, summaryY + 8, { align: "right" });
  doc.text(`${currency} ${data.customerBudget.toLocaleString()}`, 165, summaryY + 16, { align: "right" });

  if (profit >= 0) {
    doc.setTextColor(16, 185, 129);
  } else {
    doc.setTextColor(239, 68, 68);
  }
  doc.text(`${currency} ${profit.toLocaleString()}`, 165, summaryY + 28, { align: "right" });

  // Footer
  doc.setTextColor(156, 163, 175);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text("Thank you for your business!", 20, 280);
  doc.text("Generated by Wine & Food Business Intelligence OS", 20, 285);

  return doc.output("blob");
}
