/* eslint-disable @typescript-eslint/no-explicit-any */
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export interface InvoiceData {
  invoiceNumber: string;
  businessName: string;
  businessCurrency: string;
  customerName: string;
  customerPhone?: string;
  customerEmail?: string;
  date: string;
  items: {
    productName: string;
    quantity: number;
    unitPrice: number;
    total: number;
  }[];
  totalAmount: number;
}

/**
 * Generates a professional PDF invoice and returns base64 string.
 */
export function generateInvoicePDF(data: InvoiceData): string {
  const doc = new jsPDF();
  const currency = data.businessCurrency || "UGX";

  // Header background
  doc.setFillColor(17, 24, 39); // slate-900
  doc.rect(0, 0, 210, 45, "F");

  // Business name
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text(data.businessName, 20, 22);

  // Invoice label
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("INVOICE", 20, 35);

  // Invoice number & date - right side
  doc.setFontSize(10);
  doc.text(data.invoiceNumber, 160, 22);
  doc.text(data.date, 160, 30);

  // Reset text color
  doc.setTextColor(31, 41, 55);

  // Bill To section
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("BILL TO:", 20, 60);
  doc.setFont("helvetica", "normal");
  doc.text(data.customerName, 20, 68);
  if (data.customerPhone) doc.text(data.customerPhone, 20, 74);
  if (data.customerEmail) doc.text(data.customerEmail, 20, 80);

  // Items table
  const tableData = data.items.map((item, i) => [
    String(i + 1),
    item.productName,
    String(item.quantity),
    `${currency} ${item.unitPrice.toLocaleString()}`,
    `${currency} ${item.total.toLocaleString()}`,
  ]);

  autoTable(doc, {
    startY: 90,
    head: [["#", "Product", "Qty", "Unit Price", "Total"]],
    body: tableData,
    theme: "striped",
    headStyles: {
      fillColor: [17, 24, 39],
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 10,
    },
    bodyStyles: {
      fontSize: 9,
    },
    alternateRowStyles: {
      fillColor: [243, 244, 246],
    },
    columnStyles: {
      0: { cellWidth: 15 },
      1: { cellWidth: 70 },
      2: { cellWidth: 25, halign: "center" },
      3: { cellWidth: 40, halign: "right" },
      4: { cellWidth: 40, halign: "right" },
    },
  });

  // Total
  const finalY = (doc as any).lastAutoTable?.finalY || 150;
  doc.setFillColor(17, 24, 39);
  doc.rect(120, finalY + 10, 70, 12, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text(
    `TOTAL: ${currency} ${data.totalAmount.toLocaleString()}`,
    125,
    finalY + 18
  );

  // Footer
  doc.setTextColor(156, 163, 175);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text("Thank you for your business!", 20, 280);
  doc.text("Generated by Wine & Food Business Intelligence OS", 20, 285);

  return doc.output("datauristring");
}
