/* eslint-disable @typescript-eslint/no-explicit-any */
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export interface SaleReceiptData {
  businessName: string;
  businessCurrency: string;
  customerName: string;
  date: string;
  items: {
    productName: string;
    quantity: number;
    unitPrice: number;
    total: number;
  }[];
  totalAmount: number;
  receiptNumber: string;
}

export interface EventReceiptData {
  businessName: string;
  businessCurrency: string;
  customerName: string;
  eventName: string;
  eventDate: string;
  date: string;
  plateCount: number;
  totalBudget: number;
  receiptNumber: string;
}

function drawHeader(doc: jsPDF, businessName: string) {
  doc.setFillColor(17, 24, 39);
  doc.rect(0, 0, 210, 40, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text(businessName, 105, 18, { align: "center" });
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("RECEIPT", 105, 30, { align: "center" });
  doc.setTextColor(31, 41, 55);
}

function drawFooter(doc: jsPDF) {
  doc.setFillColor(17, 24, 39);
  doc.rect(0, 262, 210, 35, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.text("Thank you for supporting our business!", 105, 276, { align: "center" });
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(156, 163, 175);
  doc.text("Please keep this receipt for your records.", 105, 284, { align: "center" });
  doc.text("Generated by Wine & Food Business Intelligence OS", 105, 290, { align: "center" });
}

export function generateSaleReceipt(data: SaleReceiptData): Blob {
  const doc = new jsPDF();
  const currency = data.businessCurrency || "UGX";

  drawHeader(doc, data.businessName);

  // Meta info
  doc.setFontSize(9);
  doc.setTextColor(107, 114, 128);
  doc.text(`Receipt No: ${data.receiptNumber}`, 20, 52);
  doc.text(`Date: ${data.date}`, 20, 59);
  doc.text(`Customer: ${data.customerName}`, 20, 66);

  // Per-unit table
  const tableData = data.items.map((item) => [
    item.productName,
    item.quantity.toLocaleString(),
    `${currency} ${item.unitPrice.toLocaleString()}`,
    `${currency} ${item.total.toLocaleString()}`,
  ]);

  autoTable(doc, {
    startY: 75,
    head: [["Item", "Qty", "Unit Price", "Amount"]],
    body: tableData,
    theme: "grid",
    headStyles: {
      fillColor: [17, 24, 39],
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9,
      halign: "center",
    },
    bodyStyles: { fontSize: 9, halign: "center" },
    columnStyles: {
      0: { halign: "left", cellWidth: 70 },
      1: { cellWidth: 30 },
      2: { cellWidth: 50 },
      3: { cellWidth: 40, halign: "right" },
    },
  });

  const finalY = (doc as any).lastAutoTable?.finalY || 130;

  // Total box
  doc.setFillColor(243, 244, 246);
  doc.rect(115, finalY + 8, 75, 18, "F");
  doc.setFontSize(9);
  doc.setTextColor(107, 114, 128);
  doc.text("TOTAL PAID", 120, finalY + 15);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(17, 24, 39);
  doc.text(`${currency} ${data.totalAmount.toLocaleString()}`, 185, finalY + 22, { align: "right" });

  drawFooter(doc);

  return doc.output("blob");
}

export function generateEventReceipt(data: EventReceiptData): Blob {
  const doc = new jsPDF();
  const currency = data.businessCurrency || "UGX";

  drawHeader(doc, data.businessName);

  // Meta info
  doc.setFontSize(9);
  doc.setTextColor(107, 114, 128);
  doc.text(`Receipt No: ${data.receiptNumber}`, 20, 52);
  doc.text(`Issued: ${data.date}`, 20, 59);
  doc.text(`Customer: ${data.customerName}`, 20, 66);
  doc.text(`Event: ${data.eventName}`, 20, 73);
  doc.text(`Event Date: ${data.eventDate}`, 20, 80);

  // Per-plate breakdown table
  const perPlate = data.plateCount > 0
    ? Math.round((data.totalBudget / data.plateCount) * 100) / 100
    : 0;

  autoTable(doc, {
    startY: 90,
    head: [["Description", "Quantity", "Rate per Plate", "Total"]],
    body: [[
      `${data.eventName} — Catering Service`,
      `${data.plateCount} plates`,
      `${currency} ${perPlate.toLocaleString()}`,
      `${currency} ${data.totalBudget.toLocaleString()}`,
    ]],
    theme: "grid",
    headStyles: {
      fillColor: [17, 24, 39],
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9,
      halign: "center",
    },
    bodyStyles: { fontSize: 10, halign: "center" },
    columnStyles: {
      0: { halign: "left", cellWidth: 75 },
      1: { cellWidth: 30 },
      2: { cellWidth: 45 },
      3: { halign: "right", cellWidth: 40 },
    },
  });

  const finalY = (doc as any).lastAutoTable?.finalY || 130;

  // Plates summary highlight
  doc.setFillColor(243, 244, 246);
  doc.rect(20, finalY + 8, 170, 28, "F");
  doc.setFontSize(9);
  doc.setTextColor(107, 114, 128);
  doc.text("PLATES SERVED", 25, finalY + 16);
  doc.text("RATE PER PLATE", 90, finalY + 16);
  doc.text("TOTAL PAID", 155, finalY + 16);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(17, 24, 39);
  doc.text(String(data.plateCount), 45, finalY + 28, { align: "center" });
  doc.text(`${currency} ${perPlate.toLocaleString()}`, 110, finalY + 28, { align: "center" });
  doc.text(`${currency} ${data.totalBudget.toLocaleString()}`, 160, finalY + 28, { align: "right" });

  drawFooter(doc);

  return doc.output("blob");
}
